# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main
  - ci-cd
pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: |
      yarn install
    displayName: "install dependencies"

  - script: |
      yarn run test
    displayName: "run tests"

  - script: |
      yarn run build
    displayName: "build project"

  - script: |
      ls -R
    displayName: "ls current folder"

  - script: |
      cd .. 
      ls -R 
    displayName: "ls parent folder"
    
  - script: |
      echo $(System.DefaultWorkingDirectory)
    displayName: "echo Default Working Directory"

  - script: |
      echo $(Build.ArtifactStagingDirectory)
    displayName: "echo Artifact StagingDirectory"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/test-report.xml'

  - task: CopyFiles@2
    inputs:
      Contents: '$(System.DefaultWorkingDirectory)/dist/**' # Pull the build directory (React)
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
      ArtifactName: 'www' # output artifact named www
